export const AUDIT_ACTIONS = {
  // Authentication & User
  USER_REGISTERED: "USER_REGISTERED",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_GOOGLE_LOGIN_SUCCESS: "USER_GOOGLE_LOGIN_SUCCESS",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PROFILE_UPDATED: "PROFILE_UPDATED",
  USER_ROLE_STATUS_UPDATED: "USER_ROLE_STATUS_UPDATED",
  USER_SOFT_DELETED: "USER_SOFT_DELETED",

  // Academic Entities
  DEPARTMENT_CREATED: "DEPARTMENT_CREATED",
  DEPARTMENT_UPDATED: "DEPARTMENT_UPDATED",
  DEPARTMENT_SOFT_DELETED: "DEPARTMENT_SOFT_DELETED",

  SEMESTER_CREATED: "SEMESTER_CREATED",
  SEMESTER_UPDATED: "SEMESTER_UPDATED",
  SEMESTER_SOFT_DELETED: "SEMESTER_SOFT_DELETED",

  COURSE_CREATED: "COURSE_CREATED",
  COURSE_UPDATED: "COURSE_UPDATED",
  COURSE_SOFT_DELETED: "COURSE_SOFT_DELETED",

  COURSE_OFFERING_CREATED: "COURSE_OFFERING_CREATED",
  SECTION_CREATED: "SECTION_CREATED",
  SECTION_UPDATED: "SECTION_UPDATED",
  COURSE_OFFERING_SOFT_DELETED: "COURSE_OFFERING_SOFT_DELETED",

  // Enrollment & Grading
  COURSE_REGISTERED: "COURSE_REGISTERED",
  COURSE_WITHDRAWN: "COURSE_WITHDRAWN",
  GRADE_SUBMITTED: "GRADE_SUBMITTED",

  // Billing & Stripe Payments
  STRIPE_CHECKOUT_SESSION_CREATED: "STRIPE_CHECKOUT_SESSION_CREATED",
  TUITION_PAYMENT_COMPLETED: "TUITION_PAYMENT_COMPLETED",

  // System
  DATABASE_INITIAL_SEED: "DATABASE_INITIAL_SEED",
} as const;

export const AUDIT_RESOURCES = {
  USER: "User",
  PROFILE: "Profile",
  AUTH: "Auth",
  ACADEMIC_DEPARTMENT: "AcademicDepartment",
  ACADEMIC_SEMESTER: "AcademicSemester",
  COURSE: "Course",
  COURSE_OFFERING: "CourseOffering",
  COURSE_SECTION: "CourseSection",
  STUDENT_ENROLLMENT: "StudentEnrollment",
  STUDENT_GRADE: "StudentGrade",
  TUITION_FEE: "TuitionFee",
  PAYMENT: "Payment",
  SYSTEM: "System",
} as const;
